---
name: Env check
on:
  workflow_call:
    inputs:
      prefix:
        description: "Env parameter prefix"
        required: true
        default: "NSM_"
        type: string
jobs:
  check-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: networkservicemesh/.github
          path: .github
      - uses: actions/checkout@v4
        with:
          path: cmd
      - name: run-envcheck
        run: .github/scripts/env-check.sh cmd ${{ inputs.prefix }}
