---
name: Check generated files
on:
  workflow_call:
jobs:
  gogenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.8.0'
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - name: Install proto-gen-go
        run: go install github.com/golang/protobuf/protoc-gen-go@v1.4.2
      - name: Install go-syncmap
        run: go install github.com/searKing/golang/tools/cmd/go-syncmap@v1.1.68
      - name: Generate files
        run: go generate ./...
      - name: Check for changes in generated code
        run: |
          git diff -- '*.pb.go' || ( echo "Rerun go generate ./... locally and resubmit" && false )
          git diff -- '*.gen.go' || ( echo "Rerun go generate ./... locally and resubmit" && false )
